In [14]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


mushroom = {'number': {'e': 0, 'p':1}, 'name': {'e': 'Edible', 'p': 'Poisonous'}}

scent = {'number': {'a' : 0,'l' : 1,'c' : 2,'y' : 3,'f' : 4,'m' : 5,'n' : 6,'p' : 7,'s' : 8},
             'name': {'a' : 'Almond','l' : 'Anise','c' : 'Creosote','y' : 'Fishy',
                      'f' : 'Foul','m' : 'Musty','n' : 'None','p' : 'Pungent','s' : 'Spicy'}}

color = {'number': {'k':0,'n':1,'b':2,'h':3,'g':4,'r':5,
         'o':6,'p':7,'u':8,'e':9,'w':10,'y':11},
             'name': {'k':'Black','n':'Brown','b':'Buff','h':'Chocolate','g':'Gray','r':'Green',
         'o':'Orange','p':'Pink','u':'Purple','e':'Red','w':'White','y':'Yellow'}}

cols = ['Class Type', 'Odor', 'Gill Color']
colname = ['Class Name', 'Odor Name', 'Gill Color Name']

df = pd.read_table('agaricus-lepiota.data', delimiter=',', header=None, usecols=[0,5,9])
df.columns = cols

df["Class Type"] = df["Class Type"].map(mushroom['number'])
df["Odor"] = df["Odor"].map(scent['number'])
df["Gill Color"] = df["Gill Color"].map(color['number'])
df.head()


Class Type  Odor  Gill Color
0           1     7           0
1           0     0           0
2           0     1           1
3           1     7           1
4           0     6           0

In [23]:
dummycols = ['Odor', 'Gill Color']
X = pd.get_dummies(data=df, prefix=dummycols, prefix_sep=" ", columns=dummycols)
y = X['Class Type']
X.head()

Class Type  Odor 0  Odor 1  Odor 2  Odor 3  Odor 4  Odor 5  Odor 6  Odor 7  \
0           1       0       0       0       0       0       0       0       1   
1           0       1       0       0       0       0       0       0       0   
2           0       0       1       0       0       0       0       0       0   
3           1       0       0       0       0       0       0       0       1   
4           0       0       0       0       0       0       0       1       0   

   Odor 8  ...  Gill Color 2  Gill Color 3  Gill Color 4  Gill Color 5  \
0       0  ...             0             0             0             0   
1       0  ...             0             0             0             0   
2       0  ...             0             0             0             0   
3       0  ...             0             0             0             0   
4       0  ...             0             0             0             0   

   Gill Color 6  Gill Color 7  Gill Color 8  Gill Color 9  Gill Color 10  \
0             0             0             0             0              0   
1             0             0             0             0              0   
2             0             0             0             0              0   
3             0             0             0             0              0   
4             0             0             0             0              0   

   Gill Color 11  
0              0  
1              0  
2              0  
3              0  
4              0  

[5 rows x 22 columns]

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(6093, 22)
(6093,)
(2031, 22)
(2031,)


In [29]:
linreg = LinearRegression()
linreg.fit(X_train, y_train)
print({linreg.intercept_: linreg.coef_})

{-3.8893454037515385: array([1.        , 2.96091405, 2.96091405, 2.96091405, 2.96091405,
       2.96091405, 2.96091405, 2.96091405, 2.96091405, 2.96091405,
       0.92843135, 0.92843135, 0.92843135, 0.92843135, 0.92843135,
       0.92843135, 0.92843135, 0.92843135, 0.92843135, 0.92843135,
       0.92843135, 0.92843135])}


In [30]:
y_pred = linreg.predict(X_test)
print(metrics.mean_squared_error(y_test, y_pred))

6.472271636706219e-30


In [40]:
from sklearn import svm
from sklearn.model_selection import cross_val_score

svt = svm.SVC(probability=True, random_state=0)
svt.fit(X,y)
cross_val_score(svt, X, y, scoring='neg_mean_squared_error')

array([-0., -0., -0., -0., -0.])

In [41]:
X = pd.get_dummies(data=df, columns=['Odor'])
y = X['Class Type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
linreg.fit(X_train, y_train)
y_pred = linreg.predict(X_test)

print((metrics.mean_squared_error(y_test, y_pred)))

1.530263120174587e-29


In [43]:
svt = svm.SVC(probability=True, random_state=0)
svt.fit(X,y)
cross_val_score(svt, X, y, scoring='neg_mean_squared_error')

array([-0., -0., -0., -0., -0.])

In [45]:
X = pd.get_dummies(data=df, columns=['Gill Color'])
y = X['Class Type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
linreg.fit(X_train, y_train)
y_pred = linreg.predict(X_test)
print((metrics.mean_squared_error(y_test, y_pred)))

2.1159679586647957e-29


In [46]:
svt = svm.SVC(probability=True, random_state=0)
svt.fit(X,y)
cross_val_score(svt, X, y, scoring='neg_mean_squared_error')

array([-0., -0., -0., -0., -0.])

In [ ]:
#Based on these comparisons, the Gill Color appears to be the better predictor on knowing if a mushroom is edible or poisonous.